---
title: "ML_COVID_Memoria"
author: "Carlo Alberto Bissacco"
date: "12-01-2023"
#knit: "bookdown::render_book"
output: 
  pdf_document:
   keep_tex: yes
   toc: yes
   #rticles::elsevier_article:
   # keep_tex: true
   # citation_package: natbib
  html_document:
   toc: yes
link-citations: yes
link-bibliography : yes
notes-after-punctuation : TRUE
linkcolor: blue
abstract: |
 SCRIVERE QUI ABSTRACT pfogbkeopkgggktktkt rgortofoo 
 ooooooooooooopfeokbtprbbtotgobkovmsdvl fdkmvbsnvpgdfkfj
 nbkjgfnbgjnblkmvklgñklovkggkkkgeprokw
keywords: |
  SCRIVERE QUI KEYWARDS
csl : elsevier-with-titles.csl
bibliography: scholar1.bib
#rmd_files: ["Test.Rmd"]
---

\pagebreak

\@caret

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NULL)
```

\pagebreak

# titolo 1

## titolo2

come diceva [@obermeyer2016predicting]

come diceva @obermeyer2016predicting

come diceva anche la'ltreo idiota @couronne2018random

```{r eval=FALSE, include=FALSE}
formula(glm_aic_model)

cbind("Estimate"=coef(summary(glm_aic_model))[,1], "Odds"=exp(coef(glm_aic_model)), coef(summary(glm_aic_model))[,2:4])%>%
  kable(format="pandoc", round(3))
```

## titolo metodologia

```{r}


```

\pagebreak

# Referencias Bibliográficas
