---
title: "ML_COVID_Memoria"
author: "Carlo Alberto Bissacco"
date: "12-01-2023"
#knit: "bookdown::render_book"
output: 
  pdf_document:
   keep_tex: yes
   toc: yes
   #rticles::elsevier_article:
   # keep_tex: true
   # citation_package: natbib
  html_document:
   toc: yes
link-citations: yes
link-bibliography : yes
notes-after-punctuation : TRUE
linkcolor: blue
abstract: |
 SCRIVERE QUI ABSTRACT pfogbkeopkgggktktkt rgortofoo 
 ooooooooooooopfeokbtprbbtotgobkovmsdvl fdkmvbsnvpgdfkfj
 nbkjgfnbgjnblkmvklgñklovkggkkkgeprokw
keywords: |
  SCRIVERE QUI KEYWARDS
csl : elsevier-with-titles.csl
bibliography: scholar1.bib
#rmd_files: ["Test.Rmd"]
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NULL)
```

\pagebreak

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
library(knitr)
data_EIN_dir <- "D:/GitHub/ML_COVID/data_einstein/"
variabili <- readRDS(paste0(data_EIN_dir,"variabili.rds"))
kable(variabili, col.names = c("Columna 1", "Columna 2", "Columna 3"))
```

\pagebreak
